# Generated by Django 2.2 on 2022-01-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_added_by', to='helper_app.User'),
        ),
    ]
