# Generated by Django 2.2 on 2022-01-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0003_job_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_added_by', to='helper_app.User'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='belongs_to_user',
        ),
        migrations.AddField(
            model_name='job',
            name='belongs_to_user',
            field=models.ManyToManyField(related_name='user_jobs', to='helper_app.User'),
        ),
    ]
