# Generated by Django 2.2 on 2022-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0004_auto_20220130_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='belongs_to_user',
        ),
        migrations.AddField(
            model_name='job',
            name='belongs_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='user_jobs', to='helper_app.User'),
        ),
    ]
